#!/bin/bash
# Copyright (C) 2021 The Android Open Source Project
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#      http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

set -eux

readonly CUR_DIR="$(cd -P ${BASH_SOURCE[0]%/*}; pwd)"
readonly ROOT_DIR=$(dirname $(dirname "$CUR_DIR"))
readonly OUT_DIR="$ROOT_DIR/out/perfetto.dev"

# Build first.
rm -rf "$OUT_DIR"
"$CUR_DIR/build"

# The markdown docs are rendered into extension-less HTML files to make the URLs
# look nice (e.g., /docs/tracing rather than /docs/tracing.html). By default
# gsutil infers the mime-type from the extension, falling back to octet/stream
# for extension-less fiels. use_magicfile instead makes it use `file`.
# Unfortunately the standard `file` doesn't detect css properly so here we
# override with a custom script in mime_util/ to set the right MIME typeps.
export BOTO_CONFIG=/tmp/boto
export PATH="$CUR_DIR/mime_util:$PATH"
cat << EOF > $BOTO_CONFIG
[GSUtil]
use_magicfile = True

EOF

# Basic checks before uploading. Test both the existence and the mime type.
[ "$(file $OUT_DIR/index.html)" == "text/html" ]
[ "$(file $OUT_DIR/assets/style.css)" == "text/css" ]
[ "$(file $OUT_DIR/assets/home.png)" == "image/png" ]
[ "$(file $OUT_DIR/docs/images/perfetto-stack.svg)" == "image/svg+xml" ]
[ "$(file $OUT_DIR/docs/images/perfetto-stack.svg)" == "image/svg+xml" ]
[ "$(file $OUT_DIR/docs/analysis/sql-tables)" == "text/html" ]

# -d: mirror deletetions.
# -c: compare checksums, not mtimes.
# -r: recursive.
# -j: apply Content-Encoding gzip compression to passed extensions.
gsutil -m rsync -j html,js,css,svg -d -c -r \
  "$OUT_DIR/" gs://perfetto.dev/