#!/usr/bin/env python3

import sys
import os

def main():
  fname = None
  for arg in reversed(sys.argv[1:]):
    if os.path.exists(arg):
      fname = arg
      break
  if fname is None:
    raise 'File not found in ' + ' '.join(sys.argv)

  ext = os.path.splitext(fname)[1].lower()
  ext_map = {
    '.html': 'text/html',
    '.css': 'text/css',
    '.js': 'text/javascript',
    '.jpg': 'image/jpeg',
    '.png': 'image/png',
    '.svg': 'image/svg+xml',
  }
  print(ext_map.get(ext, 'text/html'))

if __name__ == '__main__':
  sys.exit(main())
